// Copyright (c) 2024-2026 EVtivity. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1

// AUTO-GENERATED. Do not edit by hand. Source of truth lives in the
// EVtivity website repo at app/data/error-codes.json.

/**
 * Stable machine-readable error codes returned in API `code` response field.
 * Use these constants in route schemas via `errorWith()` so OpenAPI docs show
 * the exact set of codes each endpoint can return.
 */
export const ERROR_CODES = {
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  AI_ERROR: 'AI_ERROR',
  AI_NOT_CONFIGURED: 'AI_NOT_CONFIGURED',
  ALERT_NOT_FOUND: 'ALERT_NOT_FOUND',
  ALREADY_FAVORITED: 'ALREADY_FAVORITED',
  ALREADY_VERIFIED: 'ALREADY_VERIFIED',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',
  API_KEY_RATE_LIMITED: 'API_KEY_RATE_LIMITED',
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
  ATTESTATION_FAILED: 'ATTESTATION_FAILED',
  AUDIT_ENTITY_TYPE_INVALID: 'AUDIT_ENTITY_TYPE_INVALID',
  CA_CERT_NOT_FOUND: 'CA_CERT_NOT_FOUND',
  CAMPAIGN_NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  CDR_NOT_FOUND: 'CDR_NOT_FOUND',
  CIRCUIT_NOT_FOUND: 'CIRCUIT_NOT_FOUND',
  COMMAND_ERROR: 'COMMAND_ERROR',
  COMMAND_FAILED: 'COMMAND_FAILED',
  COMMAND_QUEUED: 'COMMAND_QUEUED',
  COMMAND_TIMEOUT: 'COMMAND_TIMEOUT',
  CONNECTOR_ID_MISMATCH: 'CONNECTOR_ID_MISMATCH',
  CONNECTOR_NOT_AVAILABLE: 'CONNECTOR_NOT_AVAILABLE',
  CONNECTOR_NOT_FOUND: 'CONNECTOR_NOT_FOUND',
  CONNECTOR_OCCUPIED: 'CONNECTOR_OCCUPIED',
  CONNECTOR_RESERVED: 'CONNECTOR_RESERVED',
  CREATE_FAILED: 'CREATE_FAILED',
  CSR_NOT_FOUND: 'CSR_NOT_FOUND',
  CSRF_INVALID: 'CSRF_INVALID',
  CSS_ACTION_REJECTED: 'CSS_ACTION_REJECTED',
  CSS_ACTION_TIMEOUT: 'CSS_ACTION_TIMEOUT',
  DOWNTIME_NOT_FOUND: 'DOWNTIME_NOT_FOUND',
  DRIVER_ALREADY_IN_FLEET: 'DRIVER_ALREADY_IN_FLEET',
  DRIVER_CREATE_FAILED: 'DRIVER_CREATE_FAILED',
  DRIVER_INACTIVE: 'DRIVER_INACTIVE',
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  DUPLICATE_API_KEY_NAME: 'DUPLICATE_API_KEY_NAME',
  DUPLICATE_CONNECTOR_ID: 'DUPLICATE_CONNECTOR_ID',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_EVSE_ID: 'DUPLICATE_EVSE_ID',
  DUPLICATE_HOLIDAY: 'DUPLICATE_HOLIDAY',
  DUPLICATE_PARTNER: 'DUPLICATE_PARTNER',
  DUPLICATE_SITE_NAME: 'DUPLICATE_SITE_NAME',
  DUPLICATE_STATION_ID: 'DUPLICATE_STATION_ID',
  ELECTRICITY_RATE_NOT_FOUND: 'ELECTRICITY_RATE_NOT_FOUND',
  EMAID_PREFIX_NOT_CONFIGURED: 'EMAID_PREFIX_NOT_CONFIGURED',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  EMAIL_NOT_CONFIGURED: 'EMAIL_NOT_CONFIGURED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  ENCRYPTION_KEY_MISSING: 'ENCRYPTION_KEY_MISSING',
  EVSE_IN_USE: 'EVSE_IN_USE',
  EVSE_NOT_FOUND: 'EVSE_NOT_FOUND',
  FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',
  FLEET_BILLING_CONTACT_REQUIRED: 'FLEET_BILLING_CONTACT_REQUIRED',
  FLEET_BILLING_OLD_PODS_CONNECTED: 'FLEET_BILLING_OLD_PODS_CONNECTED',
  FLEET_CREDIT_LIMIT_REACHED: 'FLEET_CREDIT_LIMIT_REACHED',
  FLEET_DISABLED: 'FLEET_DISABLED',
  FLEET_HAS_OPEN_BILLING: 'FLEET_HAS_OPEN_BILLING',
  FLEET_INVOICE_NOTHING_TO_BILL: 'FLEET_INVOICE_NOTHING_TO_BILL',
  FLEET_INVOICE_PERIOD_EXISTS: 'FLEET_INVOICE_PERIOD_EXISTS',
  FLEET_NOT_FOUND: 'FLEET_NOT_FOUND',
  FLEET_RESERVATION_ALREADY_CANCELLED: 'FLEET_RESERVATION_ALREADY_CANCELLED',
  FLEET_RESERVATION_CREATE_FAILED: 'FLEET_RESERVATION_CREATE_FAILED',
  FLEET_RESERVATION_NOT_FOUND: 'FLEET_RESERVATION_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_DRIVER_TOKEN: 'FORBIDDEN_DRIVER_TOKEN',
  GUEST_CHARGING_DISABLED: 'GUEST_CHARGING_DISABLED',
  HOLIDAY_NOT_FOUND: 'HOLIDAY_NOT_FOUND',
  IMAGE_NOT_FOUND: 'IMAGE_NOT_FOUND',
  INSERT_FAILED: 'INSERT_FAILED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CIRCUIT: 'INVALID_CIRCUIT',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_OPERATION: 'INVALID_OPERATION',
  INVALID_PANEL: 'INVALID_PANEL',
  INVALID_PARENT_PANEL: 'INVALID_PARENT_PANEL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  INVALID_PERMISSIONS: 'INVALID_PERMISSIONS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_REGION_CODE: 'INVALID_REGION_CODE',
  INVALID_RESTRICTIONS: 'INVALID_RESTRICTIONS',
  INVALID_SITE_IDS: 'INVALID_SITE_IDS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVOICE_ALREADY_CREDITED: 'INVOICE_ALREADY_CREDITED',
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  INVOICE_CREATION_FAILED: 'INVOICE_CREATION_FAILED',
  INVOICE_IS_CREDIT_NOTE: 'INVOICE_IS_CREDIT_NOTE',
  INVOICE_NO_DRIVER: 'INVOICE_NO_DRIVER',
  INVOICE_NO_SESSIONS: 'INVOICE_NO_SESSIONS',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_NOT_ISSUED: 'INVOICE_NOT_ISSUED',
  INVOICE_NOT_VOIDABLE: 'INVOICE_NOT_VOIDABLE',
  LOAD_NOT_FOUND: 'LOAD_NOT_FOUND',
  LOCAL_CA_EXISTS: 'LOCAL_CA_EXISTS',
  LOCAL_CA_NOT_CONFIGURED: 'LOCAL_CA_NOT_CONFIGURED',
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  MAINTENANCE_ACTIVE: 'MAINTENANCE_ACTIVE',
  MAINTENANCE_ALREADY_ACTIVE: 'MAINTENANCE_ALREADY_ACTIVE',
  MAINTENANCE_INVALID_RANGE: 'MAINTENANCE_INVALID_RANGE',
  MAINTENANCE_NOT_FOUND: 'MAINTENANCE_NOT_FOUND',
  MAINTENANCE_OVERLAPS_EXISTING: 'MAINTENANCE_OVERLAPS_EXISTING',
  MAPPING_NOT_FOUND: 'MAPPING_NOT_FOUND',
  MESSAGE_CLEAR_FAILED: 'MESSAGE_CLEAR_FAILED',
  MESSAGE_CLEAR_REJECTED: 'MESSAGE_CLEAR_REJECTED',
  MESSAGE_CREATE_FAILED: 'MESSAGE_CREATE_FAILED',
  MESSAGE_NOT_CLEARABLE: 'MESSAGE_NOT_CLEARABLE',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_REFRESH_FAILED: 'MESSAGE_REFRESH_FAILED',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',
  MESSAGE_TIMEOUT: 'MESSAGE_TIMEOUT',
  MFA_ALREADY_ENABLED: 'MFA_ALREADY_ENABLED',
  MFA_CHALLENGE_EXHAUSTED: 'MFA_CHALLENGE_EXHAUSTED',
  MFA_CODE_INVALID: 'MFA_CODE_INVALID',
  MFA_METHOD_DISABLED: 'MFA_METHOD_DISABLED',
  MFA_NOT_CONFIGURED: 'MFA_NOT_CONFIGURED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_TOKEN_EXPIRED: 'MFA_TOKEN_EXPIRED',
  MFA_TOKEN_INVALID: 'MFA_TOKEN_INVALID',
  MFA_TOTP_NO_RESEND: 'MFA_TOTP_NO_RESEND',
  MISSING_PAYMENT_INTENT: 'MISSING_PAYMENT_INTENT',
  MISSING_VERSION_URL: 'MISSING_VERSION_URL',
  NO_ACTIVE_SESSION: 'NO_ACTIVE_SESSION',
  NO_CAPTURED_PAYMENT: 'NO_CAPTURED_PAYMENT',
  NO_CHARGING_SESSION: 'NO_CHARGING_SESSION',
  NO_MATCHING_TARIFF: 'NO_MATCHING_TARIFF',
  NO_PRE_AUTH: 'NO_PRE_AUTH',
  NO_PRICING_GROUP: 'NO_PRICING_GROUP',
  NO_REFRESH_TOKEN: 'NO_REFRESH_TOKEN',
  NO_TARGETS: 'NO_TARGETS',
  NO_TARIFFS: 'NO_TARIFFS',
  NO_VALID_ENTRIES: 'NO_VALID_ENTRIES',
  NO_VALID_TOKENS: 'NO_VALID_TOKENS',
  NOT_BLOCKED: 'NOT_BLOCKED',
  NOT_CHARGING: 'NOT_CHARGING',
  NOT_DRAFT: 'NOT_DRAFT',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  NOT_PENDING: 'NOT_PENDING',
  NOT_SUPPORTED: 'NOT_SUPPORTED',
  NOTIFICATION_EVENT_REQUIRED: 'NOTIFICATION_EVENT_REQUIRED',
  OCPP_COMMAND_FAILED: 'OCPP_COMMAND_FAILED',
  OCPP_VERSION_MISMATCH: 'OCPP_VERSION_MISMATCH',
  OCTT_RUN_NOT_FOUND: 'OCTT_RUN_NOT_FOUND',
  OVERSUBSCRIPTION_EXCEEDED: 'OVERSUBSCRIPTION_EXCEEDED',
  PANEL_NOT_FOUND: 'PANEL_NOT_FOUND',
  PARTNER_NOT_CONNECTED: 'PARTNER_NOT_CONNECTED',
  PARTNER_NOT_FOUND: 'PARTNER_NOT_FOUND',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  PAYMENT_CONFIG_NOT_FOUND: 'PAYMENT_CONFIG_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_METHOD_IN_USE: 'PAYMENT_METHOD_IN_USE',
  PAYMENT_METHOD_NOT_FOUND: 'PAYMENT_METHOD_NOT_FOUND',
  PAYMENT_METHOD_REQUIRED: 'PAYMENT_METHOD_REQUIRED',
  PAYMENT_NOT_CONFIGURED: 'PAYMENT_NOT_CONFIGURED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_OPERATION_PENDING: 'PAYMENT_OPERATION_PENDING',
  PAYMENT_PREAUTH_FAILED: 'PAYMENT_PREAUTH_FAILED',
  PAYMENT_PROVIDER_CONNECTION_FAILED: 'PAYMENT_PROVIDER_CONNECTION_FAILED',
  PAYMENT_PROVIDER_NOT_CONFIGURED: 'PAYMENT_PROVIDER_NOT_CONFIGURED',
  PAYMENT_PROVIDER_PERMISSION_MISSING: 'PAYMENT_PROVIDER_PERMISSION_MISSING',
  PAYMENT_PROVIDER_UPGRADE_PENDING: 'PAYMENT_PROVIDER_UPGRADE_PENDING',
  PAYMENT_RECORD_NOT_RECOVERABLE: 'PAYMENT_RECORD_NOT_RECOVERABLE',
  PAYMENT_TOP_UP_FAILED: 'PAYMENT_TOP_UP_FAILED',
  PAYMENT_WEBHOOK_EXISTS: 'PAYMENT_WEBHOOK_EXISTS',
  PAYOUT_ACCOUNT_EXISTS: 'PAYOUT_ACCOUNT_EXISTS',
  PAYOUT_ACCOUNT_NOT_READY: 'PAYOUT_ACCOUNT_NOT_READY',
  PERMISSIONS_EXCEED_OWN: 'PERMISSIONS_EXCEED_OWN',
  PHONE_REGISTRATION_LIMITED: 'PHONE_REGISTRATION_LIMITED',
  PKI_ROOT_REFRESH_FAILED: 'PKI_ROOT_REFRESH_FAILED',
  PNC_CONTRACT_NOT_FOUND: 'PNC_CONTRACT_NOT_FOUND',
  PNC_DISABLED: 'PNC_DISABLED',
  PORTAL_ALREADY_ACTIVE: 'PORTAL_ALREADY_ACTIVE',
  PORTAL_REGISTRATION_DISABLED: 'PORTAL_REGISTRATION_DISABLED',
  PRE_AUTH_FAILED: 'PRE_AUTH_FAILED',
  PRICING_ASSIGNMENT_NOT_FOUND: 'PRICING_ASSIGNMENT_NOT_FOUND',
  PRICING_GROUP_NOT_FOUND: 'PRICING_GROUP_NOT_FOUND',
  PRICING_GROUP_TARIFFS_IN_USE: 'PRICING_GROUP_TARIFFS_IN_USE',
  PRICING_NOT_FOUND: 'PRICING_NOT_FOUND',
  PRIVATE_URL: 'PRIVATE_URL',
  PROFILE_ID_ALLOC_FAILED: 'PROFILE_ID_ALLOC_FAILED',
  PROFILE_ID_IN_USE: 'PROFILE_ID_IN_USE',
  PROVIDER_TEST_FAILED: 'PROVIDER_TEST_FAILED',
  PUSH_NOT_FOUND: 'PUSH_NOT_FOUND',
  PUSH_REJECTED: 'PUSH_REJECTED',
  RATE_LIMITED: 'RATE_LIMITED',
  RECAPTCHA_FAILED: 'RECAPTCHA_FAILED',
  RECAPTCHA_REQUIRED: 'RECAPTCHA_REQUIRED',
  RECAPTCHA_SECRET_REQUIRED: 'RECAPTCHA_SECRET_REQUIRED',
  REFUND_EXCEEDS_REMAINING: 'REFUND_EXCEEDS_REMAINING',
  REFUND_TOP_UP_UNKNOWN: 'REFUND_TOP_UP_UNKNOWN',
  REGION_NOT_FOUND: 'REGION_NOT_FOUND',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  RESERVATION_BUFFER_ACTIVE: 'RESERVATION_BUFFER_ACTIVE',
  RESERVATION_CONFLICT: 'RESERVATION_CONFLICT',
  RESERVATION_CREATE_FAILED: 'RESERVATION_CREATE_FAILED',
  RESERVATION_DISABLED: 'RESERVATION_DISABLED',
  RESERVATION_DURING_MAINTENANCE: 'RESERVATION_DURING_MAINTENANCE',
  RESERVATION_EXPIRES_TOO_SOON: 'RESERVATION_EXPIRES_TOO_SOON',
  RESERVATION_NOT_ACTIVE: 'RESERVATION_NOT_ACTIVE',
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  RESERVATION_REJECTED: 'RESERVATION_REJECTED',
  RESERVATION_STARTS_IN_PAST: 'RESERVATION_STARTS_IN_PAST',
  RESERVATION_TIMEOUT: 'RESERVATION_TIMEOUT',
  RESERVATION_TOO_LONG: 'RESERVATION_TOO_LONG',
  RESERVATION_WINDOW_TOO_SHORT: 'RESERVATION_WINDOW_TOO_SHORT',
  RESET_NOT_REQUIRED: 'RESET_NOT_REQUIRED',
  ROAMING_DISABLED: 'ROAMING_DISABLED',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROTATION_NOT_APPLICABLE: 'ROTATION_NOT_APPLICABLE',
  RULE_NOT_FOUND: 'RULE_NOT_FOUND',
  SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
  SCHEMA_NOT_FOUND: 'SCHEMA_NOT_FOUND',
  SECURITY_PROFILE_DOWNGRADE: 'SECURITY_PROFILE_DOWNGRADE',
  SELF_EDIT_FORBIDDEN: 'SELF_EDIT_FORBIDDEN',
  SESSION_ALREADY_ACTIVE: 'SESSION_ALREADY_ACTIVE',
  SESSION_CREATE_FAILED: 'SESSION_CREATE_FAILED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_NOT_LINKED: 'SESSION_NOT_LINKED',
  SESSION_REBILL_IN_PROGRESS: 'SESSION_REBILL_IN_PROGRESS',
  SESSION_REBILL_NOT_ELIGIBLE: 'SESSION_REBILL_NOT_ELIGIBLE',
  SESSION_REBILL_PAYMENT_PENDING: 'SESSION_REBILL_PAYMENT_PENDING',
  SETTING_NOT_FOUND: 'SETTING_NOT_FOUND',
  SITE_HAS_STATIONS: 'SITE_HAS_STATIONS',
  SITE_NOT_FOUND: 'SITE_NOT_FOUND',
  SITE_PAYMENT_CONFIG_IN_USE: 'SITE_PAYMENT_CONFIG_IN_USE',
  SMS_NOT_CONFIGURED: 'SMS_NOT_CONFIGURED',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',
  SSO_DISABLED: 'SSO_DISABLED',
  START_REJECTED: 'START_REJECTED',
  STATION_ALREADY_AVAILABLE: 'STATION_ALREADY_AVAILABLE',
  STATION_ALREADY_IN_FLEET: 'STATION_ALREADY_IN_FLEET',
  STATION_ID_EXISTS: 'STATION_ID_EXISTS',
  STATION_NOT_FOUND: 'STATION_NOT_FOUND',
  STATION_OFFLINE: 'STATION_OFFLINE',
  STATION_REJECTED: 'STATION_REJECTED',
  STATION_SECURITY_CHANGE_REJECTED: 'STATION_SECURITY_CHANGE_REJECTED',
  STATION_TIMEOUT: 'STATION_TIMEOUT',
  STATION_TLS_URL_NOT_CONFIGURED: 'STATION_TLS_URL_NOT_CONFIGURED',
  STATION_UNAVAILABLE: 'STATION_UNAVAILABLE',
  STATION_WATCH_NOT_FOUND: 'STATION_WATCH_NOT_FOUND',
  STATUS_CHECK_REJECTED: 'STATUS_CHECK_REJECTED',
  STATUS_CHECK_TIMEOUT: 'STATUS_CHECK_TIMEOUT',
  STORAGE_CONNECTION_FAILED: 'STORAGE_CONNECTION_FAILED',
  STORAGE_NOT_CONFIGURED: 'STORAGE_NOT_CONFIGURED',
  SUPPORT_AI_NOT_CONFIGURED: 'SUPPORT_AI_NOT_CONFIGURED',
  SUPPORT_CASE_NOT_FOUND: 'SUPPORT_CASE_NOT_FOUND',
  SUPPORT_DISABLED: 'SUPPORT_DISABLED',
  TARIFF_IN_USE: 'TARIFF_IN_USE',
  TARIFF_NOT_FOUND: 'TARIFF_NOT_FOUND',
  TARIFF_OVERLAP: 'TARIFF_OVERLAP',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TOKEN_DUPLICATE: 'TOKEN_DUPLICATE',
  TOKEN_IN_USE: 'TOKEN_IN_USE',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  TOO_MANY_WATCHES: 'TOO_MANY_WATCHES',
  TOTP_NOT_CONFIGURED: 'TOTP_NOT_CONFIGURED',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  UNKNOWN_ACTION: 'UNKNOWN_ACTION',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',
  VENDOR_NOT_FOUND: 'VENDOR_NOT_FOUND',
  VERIFICATION_RESEND_LIMITED: 'VERIFICATION_RESEND_LIMITED',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  WEBHOOK_NOT_CONFIGURED: 'WEBHOOK_NOT_CONFIGURED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_SIGNATURE_MISSING: 'WEBHOOK_SIGNATURE_MISSING',
} as const;

export type ErrorCode =
  | 'ACCOUNT_DEACTIVATED'
  | 'ACCOUNT_DISABLED'
  | 'AI_ERROR'
  | 'AI_NOT_CONFIGURED'
  | 'ALERT_NOT_FOUND'
  | 'ALREADY_FAVORITED'
  | 'ALREADY_VERIFIED'
  | 'API_KEY_EXPIRED'
  | 'API_KEY_NOT_FOUND'
  | 'API_KEY_RATE_LIMITED'
  | 'ATTACHMENT_NOT_FOUND'
  | 'ATTESTATION_FAILED'
  | 'AUDIT_ENTITY_TYPE_INVALID'
  | 'CA_CERT_NOT_FOUND'
  | 'CAMPAIGN_NOT_FOUND'
  | 'CASE_NOT_FOUND'
  | 'CDR_NOT_FOUND'
  | 'CIRCUIT_NOT_FOUND'
  | 'COMMAND_ERROR'
  | 'COMMAND_FAILED'
  | 'COMMAND_QUEUED'
  | 'COMMAND_TIMEOUT'
  | 'CONNECTOR_ID_MISMATCH'
  | 'CONNECTOR_NOT_AVAILABLE'
  | 'CONNECTOR_NOT_FOUND'
  | 'CONNECTOR_OCCUPIED'
  | 'CONNECTOR_RESERVED'
  | 'CREATE_FAILED'
  | 'CSR_NOT_FOUND'
  | 'CSRF_INVALID'
  | 'CSS_ACTION_REJECTED'
  | 'CSS_ACTION_TIMEOUT'
  | 'DOWNTIME_NOT_FOUND'
  | 'DRIVER_ALREADY_IN_FLEET'
  | 'DRIVER_CREATE_FAILED'
  | 'DRIVER_INACTIVE'
  | 'DRIVER_NOT_FOUND'
  | 'DUPLICATE_API_KEY_NAME'
  | 'DUPLICATE_CONNECTOR_ID'
  | 'DUPLICATE_EMAIL'
  | 'DUPLICATE_EVSE_ID'
  | 'DUPLICATE_HOLIDAY'
  | 'DUPLICATE_PARTNER'
  | 'DUPLICATE_SITE_NAME'
  | 'DUPLICATE_STATION_ID'
  | 'ELECTRICITY_RATE_NOT_FOUND'
  | 'EMAID_PREFIX_NOT_CONFIGURED'
  | 'EMAIL_EXISTS'
  | 'EMAIL_NOT_CONFIGURED'
  | 'EMAIL_NOT_VERIFIED'
  | 'EMAIL_REQUIRED'
  | 'EMAIL_SEND_FAILED'
  | 'ENCRYPTION_KEY_MISSING'
  | 'EVSE_IN_USE'
  | 'EVSE_NOT_FOUND'
  | 'FAVORITE_NOT_FOUND'
  | 'FLEET_BILLING_CONTACT_REQUIRED'
  | 'FLEET_BILLING_OLD_PODS_CONNECTED'
  | 'FLEET_CREDIT_LIMIT_REACHED'
  | 'FLEET_DISABLED'
  | 'FLEET_HAS_OPEN_BILLING'
  | 'FLEET_INVOICE_NOTHING_TO_BILL'
  | 'FLEET_INVOICE_PERIOD_EXISTS'
  | 'FLEET_NOT_FOUND'
  | 'FLEET_RESERVATION_ALREADY_CANCELLED'
  | 'FLEET_RESERVATION_CREATE_FAILED'
  | 'FLEET_RESERVATION_NOT_FOUND'
  | 'FORBIDDEN'
  | 'FORBIDDEN_DRIVER_TOKEN'
  | 'GUEST_CHARGING_DISABLED'
  | 'HOLIDAY_NOT_FOUND'
  | 'IMAGE_NOT_FOUND'
  | 'INSERT_FAILED'
  | 'INSUFFICIENT_PERMISSIONS'
  | 'INTERNAL_ERROR'
  | 'INVALID_CIRCUIT'
  | 'INVALID_CREDENTIALS'
  | 'INVALID_OPERATION'
  | 'INVALID_PANEL'
  | 'INVALID_PARENT_PANEL'
  | 'INVALID_PASSWORD'
  | 'INVALID_PAYLOAD'
  | 'INVALID_PERMISSIONS'
  | 'INVALID_REFRESH_TOKEN'
  | 'INVALID_REGION_CODE'
  | 'INVALID_RESTRICTIONS'
  | 'INVALID_SITE_IDS'
  | 'INVALID_TOKEN'
  | 'INVOICE_ALREADY_CREDITED'
  | 'INVOICE_ALREADY_PAID'
  | 'INVOICE_CREATION_FAILED'
  | 'INVOICE_IS_CREDIT_NOTE'
  | 'INVOICE_NO_DRIVER'
  | 'INVOICE_NO_SESSIONS'
  | 'INVOICE_NOT_FOUND'
  | 'INVOICE_NOT_ISSUED'
  | 'INVOICE_NOT_VOIDABLE'
  | 'LOAD_NOT_FOUND'
  | 'LOCAL_CA_EXISTS'
  | 'LOCAL_CA_NOT_CONFIGURED'
  | 'LOCATION_NOT_FOUND'
  | 'MAINTENANCE_ACTIVE'
  | 'MAINTENANCE_ALREADY_ACTIVE'
  | 'MAINTENANCE_INVALID_RANGE'
  | 'MAINTENANCE_NOT_FOUND'
  | 'MAINTENANCE_OVERLAPS_EXISTING'
  | 'MAPPING_NOT_FOUND'
  | 'MESSAGE_CLEAR_FAILED'
  | 'MESSAGE_CLEAR_REJECTED'
  | 'MESSAGE_CREATE_FAILED'
  | 'MESSAGE_NOT_CLEARABLE'
  | 'MESSAGE_NOT_FOUND'
  | 'MESSAGE_REFRESH_FAILED'
  | 'MESSAGE_SEND_FAILED'
  | 'MESSAGE_TIMEOUT'
  | 'MFA_ALREADY_ENABLED'
  | 'MFA_CHALLENGE_EXHAUSTED'
  | 'MFA_CODE_INVALID'
  | 'MFA_METHOD_DISABLED'
  | 'MFA_NOT_CONFIGURED'
  | 'MFA_REQUIRED'
  | 'MFA_TOKEN_EXPIRED'
  | 'MFA_TOKEN_INVALID'
  | 'MFA_TOTP_NO_RESEND'
  | 'MISSING_PAYMENT_INTENT'
  | 'MISSING_VERSION_URL'
  | 'NO_ACTIVE_SESSION'
  | 'NO_CAPTURED_PAYMENT'
  | 'NO_CHARGING_SESSION'
  | 'NO_MATCHING_TARIFF'
  | 'NO_PRE_AUTH'
  | 'NO_PRICING_GROUP'
  | 'NO_REFRESH_TOKEN'
  | 'NO_TARGETS'
  | 'NO_TARIFFS'
  | 'NO_VALID_ENTRIES'
  | 'NO_VALID_TOKENS'
  | 'NOT_BLOCKED'
  | 'NOT_CHARGING'
  | 'NOT_DRAFT'
  | 'NOT_IMPLEMENTED'
  | 'NOT_PENDING'
  | 'NOT_SUPPORTED'
  | 'NOTIFICATION_EVENT_REQUIRED'
  | 'OCPP_COMMAND_FAILED'
  | 'OCPP_VERSION_MISMATCH'
  | 'OCTT_RUN_NOT_FOUND'
  | 'OVERSUBSCRIPTION_EXCEEDED'
  | 'PANEL_NOT_FOUND'
  | 'PARTNER_NOT_CONNECTED'
  | 'PARTNER_NOT_FOUND'
  | 'PASSWORD_REQUIRED'
  | 'PAYMENT_CONFIG_NOT_FOUND'
  | 'PAYMENT_FAILED'
  | 'PAYMENT_METHOD_IN_USE'
  | 'PAYMENT_METHOD_NOT_FOUND'
  | 'PAYMENT_METHOD_REQUIRED'
  | 'PAYMENT_NOT_CONFIGURED'
  | 'PAYMENT_NOT_FOUND'
  | 'PAYMENT_OPERATION_PENDING'
  | 'PAYMENT_PREAUTH_FAILED'
  | 'PAYMENT_PROVIDER_CONNECTION_FAILED'
  | 'PAYMENT_PROVIDER_NOT_CONFIGURED'
  | 'PAYMENT_PROVIDER_PERMISSION_MISSING'
  | 'PAYMENT_PROVIDER_UPGRADE_PENDING'
  | 'PAYMENT_RECORD_NOT_RECOVERABLE'
  | 'PAYMENT_TOP_UP_FAILED'
  | 'PAYMENT_WEBHOOK_EXISTS'
  | 'PAYOUT_ACCOUNT_EXISTS'
  | 'PAYOUT_ACCOUNT_NOT_READY'
  | 'PERMISSIONS_EXCEED_OWN'
  | 'PHONE_REGISTRATION_LIMITED'
  | 'PKI_ROOT_REFRESH_FAILED'
  | 'PNC_CONTRACT_NOT_FOUND'
  | 'PNC_DISABLED'
  | 'PORTAL_ALREADY_ACTIVE'
  | 'PORTAL_REGISTRATION_DISABLED'
  | 'PRE_AUTH_FAILED'
  | 'PRICING_ASSIGNMENT_NOT_FOUND'
  | 'PRICING_GROUP_NOT_FOUND'
  | 'PRICING_GROUP_TARIFFS_IN_USE'
  | 'PRICING_NOT_FOUND'
  | 'PRIVATE_URL'
  | 'PROFILE_ID_ALLOC_FAILED'
  | 'PROFILE_ID_IN_USE'
  | 'PROVIDER_TEST_FAILED'
  | 'PUSH_NOT_FOUND'
  | 'PUSH_REJECTED'
  | 'RATE_LIMITED'
  | 'RECAPTCHA_FAILED'
  | 'RECAPTCHA_REQUIRED'
  | 'RECAPTCHA_SECRET_REQUIRED'
  | 'REFUND_EXCEEDS_REMAINING'
  | 'REFUND_TOP_UP_UNKNOWN'
  | 'REGION_NOT_FOUND'
  | 'REPORT_NOT_FOUND'
  | 'RESERVATION_BUFFER_ACTIVE'
  | 'RESERVATION_CONFLICT'
  | 'RESERVATION_CREATE_FAILED'
  | 'RESERVATION_DISABLED'
  | 'RESERVATION_DURING_MAINTENANCE'
  | 'RESERVATION_EXPIRES_TOO_SOON'
  | 'RESERVATION_NOT_ACTIVE'
  | 'RESERVATION_NOT_FOUND'
  | 'RESERVATION_REJECTED'
  | 'RESERVATION_STARTS_IN_PAST'
  | 'RESERVATION_TIMEOUT'
  | 'RESERVATION_TOO_LONG'
  | 'RESERVATION_WINDOW_TOO_SHORT'
  | 'RESET_NOT_REQUIRED'
  | 'ROAMING_DISABLED'
  | 'ROLE_NOT_FOUND'
  | 'ROTATION_NOT_APPLICABLE'
  | 'RULE_NOT_FOUND'
  | 'SCHEDULE_NOT_FOUND'
  | 'SCHEMA_NOT_FOUND'
  | 'SECURITY_PROFILE_DOWNGRADE'
  | 'SELF_EDIT_FORBIDDEN'
  | 'SESSION_ALREADY_ACTIVE'
  | 'SESSION_CREATE_FAILED'
  | 'SESSION_NOT_FOUND'
  | 'SESSION_NOT_LINKED'
  | 'SESSION_REBILL_IN_PROGRESS'
  | 'SESSION_REBILL_NOT_ELIGIBLE'
  | 'SESSION_REBILL_PAYMENT_PENDING'
  | 'SETTING_NOT_FOUND'
  | 'SITE_HAS_STATIONS'
  | 'SITE_NOT_FOUND'
  | 'SITE_PAYMENT_CONFIG_IN_USE'
  | 'SMS_NOT_CONFIGURED'
  | 'SMS_SEND_FAILED'
  | 'SSO_DISABLED'
  | 'START_REJECTED'
  | 'STATION_ALREADY_AVAILABLE'
  | 'STATION_ALREADY_IN_FLEET'
  | 'STATION_ID_EXISTS'
  | 'STATION_NOT_FOUND'
  | 'STATION_OFFLINE'
  | 'STATION_REJECTED'
  | 'STATION_SECURITY_CHANGE_REJECTED'
  | 'STATION_TIMEOUT'
  | 'STATION_TLS_URL_NOT_CONFIGURED'
  | 'STATION_UNAVAILABLE'
  | 'STATION_WATCH_NOT_FOUND'
  | 'STATUS_CHECK_REJECTED'
  | 'STATUS_CHECK_TIMEOUT'
  | 'STORAGE_CONNECTION_FAILED'
  | 'STORAGE_NOT_CONFIGURED'
  | 'SUPPORT_AI_NOT_CONFIGURED'
  | 'SUPPORT_CASE_NOT_FOUND'
  | 'SUPPORT_DISABLED'
  | 'TARIFF_IN_USE'
  | 'TARIFF_NOT_FOUND'
  | 'TARIFF_OVERLAP'
  | 'TEMPLATE_NOT_FOUND'
  | 'TOKEN_DUPLICATE'
  | 'TOKEN_IN_USE'
  | 'TOKEN_NOT_FOUND'
  | 'TOO_MANY_WATCHES'
  | 'TOTP_NOT_CONFIGURED'
  | 'TRANSACTION_NOT_FOUND'
  | 'UNAUTHORIZED'
  | 'UNKNOWN_ACTION'
  | 'USER_NOT_FOUND'
  | 'VALIDATION_ERROR'
  | 'VEHICLE_NOT_FOUND'
  | 'VENDOR_NOT_FOUND'
  | 'VERIFICATION_RESEND_LIMITED'
  | 'WEAK_PASSWORD'
  | 'WEBHOOK_NOT_CONFIGURED'
  | 'WEBHOOK_SIGNATURE_INVALID'
  | 'WEBHOOK_SIGNATURE_MISSING';

export const ALL_ERROR_CODES: readonly ErrorCode[] = Object.values(ERROR_CODES);

/**
 * Default English error messages keyed by code. Used by `errorWith()` to
 * surface the actual returned message text in OpenAPI `error` field
 * descriptions instead of a generic placeholder. Translations live in the
 * frontend i18n bundles; this is the server-side fallback string.
 */
export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  ACCOUNT_DEACTIVATED: 'Account deactivated',
  ACCOUNT_DISABLED: 'Account disabled',
  AI_ERROR: 'Failed to process AI request',
  AI_NOT_CONFIGURED: 'AI is not configured',
  ALERT_NOT_FOUND: 'Alert not found',
  ALREADY_FAVORITED: 'Already favorited',
  ALREADY_VERIFIED: 'Email already verified',
  API_KEY_EXPIRED: 'API key expired',
  API_KEY_NOT_FOUND: 'API key not found',
  API_KEY_RATE_LIMITED: 'API key rate limit exceeded',
  ATTACHMENT_NOT_FOUND: 'Attachment not found',
  ATTESTATION_FAILED: 'Device attestation failed. Update the app and try again.',
  AUDIT_ENTITY_TYPE_INVALID: 'Unknown audit entity type',
  CA_CERT_NOT_FOUND: 'CA certificate not found',
  CAMPAIGN_NOT_FOUND: 'Campaign not found',
  CASE_NOT_FOUND: 'Case not found',
  CDR_NOT_FOUND: 'CDR not found',
  CIRCUIT_NOT_FOUND: 'Circuit not found',
  COMMAND_ERROR: 'Command failed',
  COMMAND_FAILED: 'Command failed',
  COMMAND_QUEUED: 'Station offline, command queued',
  COMMAND_TIMEOUT: 'Command timed out',
  CONNECTOR_ID_MISMATCH:
    'An OCPP 1.6 EVSE has exactly one connector with the same number as the EVSE',
  CONNECTOR_NOT_AVAILABLE: 'Connector is not available for charging',
  CONNECTOR_NOT_FOUND: 'Connector not found',
  CONNECTOR_OCCUPIED: 'Cannot delete EVSE with occupied connectors',
  CONNECTOR_RESERVED: 'Connector is reserved for another driver',
  CREATE_FAILED: 'Failed to create circuit',
  CSR_NOT_FOUND: 'Pending CSR not found',
  CSRF_INVALID: 'Invalid CSRF token',
  CSS_ACTION_REJECTED: 'Charging Station Simulator rejected the action',
  CSS_ACTION_TIMEOUT: 'Simulator did not respond within 5s',
  DOWNTIME_NOT_FOUND: 'Excluded downtime record not found',
  DRIVER_ALREADY_IN_FLEET: 'Driver is already in this fleet',
  DRIVER_CREATE_FAILED: 'Failed to create driver',
  DRIVER_INACTIVE: 'Driver is inactive',
  DRIVER_NOT_FOUND: 'Driver not found',
  DUPLICATE_API_KEY_NAME: 'An API key with this name already exists',
  DUPLICATE_CONNECTOR_ID: 'Connector ID ... already exists on this EVSE',
  DUPLICATE_EMAIL: 'Email already in use',
  DUPLICATE_EVSE_ID: 'EVSE ID ... already exists on this station',
  DUPLICATE_HOLIDAY: 'A holiday already exists for this date',
  DUPLICATE_PARTNER: 'Partner with this country code and party ID already exists',
  DUPLICATE_SITE_NAME: 'A site with this name already exists',
  DUPLICATE_STATION_ID: 'Station ID already exists',
  ELECTRICITY_RATE_NOT_FOUND: 'Electricity rate not found',
  EMAID_PREFIX_NOT_CONFIGURED: 'Set the eMAID country code and provider ID first',
  EMAIL_EXISTS: 'Email already registered',
  EMAIL_NOT_CONFIGURED: 'Email provider not configured',
  EMAIL_NOT_VERIFIED: 'Email not verified',
  EMAIL_REQUIRED: 'Email required for paid charging',
  EMAIL_SEND_FAILED: 'Failed to send email',
  ENCRYPTION_KEY_MISSING: 'SETTINGS_ENCRYPTION_KEY not configured on server',
  EVSE_IN_USE: 'Another session is already active on this connector',
  EVSE_NOT_FOUND: 'EVSE not found',
  FAVORITE_NOT_FOUND: 'Favorite not found',
  FLEET_BILLING_CONTACT_REQUIRED:
    'The fleet needs at least one billing contact for automatic invoicing and invoice emails.',
  FLEET_BILLING_OLD_PODS_CONNECTED:
    'A process older than v0.1.41 is still connected. Finish the upgrade, then turn on account billing.',
  FLEET_CREDIT_LIMIT_REACHED:
    'The credit limit of the fleet your sessions are billed to is reached. Contact your fleet manager.',
  FLEET_DISABLED: 'Fleet is disabled',
  FLEET_HAS_OPEN_BILLING:
    'The fleet has sessions billed to its account and cannot be deleted. Turn off account billing instead.',
  FLEET_INVOICE_NOTHING_TO_BILL:
    'The fleet has no unbilled sessions with a cost to invoice for this period.',
  FLEET_INVOICE_PERIOD_EXISTS:
    'The fleet already has an invoice for this period. Credit it to bill the period again.',
  FLEET_NOT_FOUND: 'Fleet not found',
  FLEET_RESERVATION_ALREADY_CANCELLED: 'Fleet reservation is already cancelled',
  FLEET_RESERVATION_CREATE_FAILED: 'Failed to create fleet reservation',
  FLEET_RESERVATION_NOT_FOUND: 'Fleet reservation not found',
  FORBIDDEN: 'Forbidden',
  FORBIDDEN_DRIVER_TOKEN: 'Forbidden: driver token required',
  GUEST_CHARGING_DISABLED: 'Guest charging is disabled',
  HOLIDAY_NOT_FOUND: 'Holiday not found',
  IMAGE_NOT_FOUND: 'Image not found',
  INSERT_FAILED: 'Failed to create run',
  INSUFFICIENT_PERMISSIONS: 'Insufficient permissions',
  INTERNAL_ERROR: 'Internal server error',
  INVALID_CIRCUIT: 'Circuit not found in this site',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_OPERATION: 'Cannot credit a credit CDR',
  INVALID_PANEL: 'Panel not found in this site',
  INVALID_PARENT_PANEL: 'Parent panel not found in this site',
  INVALID_PASSWORD: 'Current password is incorrect',
  INVALID_PAYLOAD: 'The OCPP command payload is invalid',
  INVALID_PERMISSIONS: 'Invalid permissions: ...',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  INVALID_REGION_CODE: 'Invalid region code',
  INVALID_RESTRICTIONS: 'Invalid tariff restrictions',
  INVALID_SITE_IDS: 'One or more siteIds do not exist',
  INVALID_TOKEN: 'Invalid or expired reset link',
  INVOICE_ALREADY_CREDITED: 'The invoice is already credited by a credit note',
  INVOICE_ALREADY_PAID: 'The invoice is already paid',
  INVOICE_CREATION_FAILED: 'Failed to create invoice',
  INVOICE_IS_CREDIT_NOTE: 'A credit note cannot be marked paid or credited',
  INVOICE_NO_DRIVER: 'This invoice has no driver to send to',
  INVOICE_NO_SESSIONS: 'No uninvoiced sessions found for this driver in the selected date range',
  INVOICE_NOT_FOUND: 'Invoice not found',
  INVOICE_NOT_ISSUED: 'The invoice must be issued for this action',
  INVOICE_NOT_VOIDABLE:
    'Only a draft invoice can be voided. Correct an issued invoice with a credit note',
  LOAD_NOT_FOUND: 'Load not found',
  LOCAL_CA_EXISTS: 'A local contract CA already exists',
  LOCAL_CA_NOT_CONFIGURED: 'Create the local contract CA first',
  LOCATION_NOT_FOUND: 'Location not found',
  MAINTENANCE_ACTIVE: 'Site is currently under maintenance',
  MAINTENANCE_ALREADY_ACTIVE: 'Maintenance event is already active',
  MAINTENANCE_INVALID_RANGE: 'Maintenance end must be after start',
  MAINTENANCE_NOT_FOUND: 'Maintenance event not found',
  MAINTENANCE_OVERLAPS_EXISTING: 'Maintenance window overlaps an existing event',
  MAPPING_NOT_FOUND: 'Tariff mapping not found',
  MESSAGE_CLEAR_FAILED: 'Failed to clear display message',
  MESSAGE_CLEAR_REJECTED: 'Station rejected clear: ...',
  MESSAGE_CREATE_FAILED: 'Failed to create message',
  MESSAGE_NOT_CLEARABLE: 'Only accepted messages can be cleared',
  MESSAGE_NOT_FOUND: 'Message not found',
  MESSAGE_REFRESH_FAILED: 'Failed to refresh display messages',
  MESSAGE_SEND_FAILED: 'Failed to send display message',
  MESSAGE_TIMEOUT: 'Display message command timed out',
  MFA_ALREADY_ENABLED: 'MFA is already enabled. Disable it first before setting up a new method.',
  MFA_CHALLENGE_EXHAUSTED: 'Too many failed attempts. Request a new code.',
  MFA_CODE_INVALID: 'Invalid verification code',
  MFA_METHOD_DISABLED: 'MFA method is disabled',
  MFA_NOT_CONFIGURED: 'MFA not configured',
  MFA_REQUIRED: 'MFA verification required',
  MFA_TOKEN_EXPIRED: 'Invalid or expired MFA token',
  MFA_TOKEN_INVALID: 'Invalid MFA token',
  MFA_TOTP_NO_RESEND: 'Cannot resend TOTP codes',
  MISSING_PAYMENT_INTENT: 'Payment intent missing',
  MISSING_VERSION_URL: 'Partner version URL is required for registration',
  NO_ACTIVE_SESSION: 'No active session on this EVSE',
  NO_CAPTURED_PAYMENT: 'No captured payment to refund',
  NO_CHARGING_SESSION: 'No linked charging session',
  NO_MATCHING_TARIFF: 'No matching tariff for current time',
  NO_PRE_AUTH: 'No pre-authorized payment for this session',
  NO_PRICING_GROUP: 'No pricing group found for station',
  NO_REFRESH_TOKEN: 'No refresh token',
  NO_TARGETS: 'No matching stations found',
  NO_TARIFFS: 'No active tariffs found',
  NO_VALID_ENTRIES: 'No valid entries found',
  NO_VALID_TOKENS: 'No valid tokens found',
  NOT_BLOCKED: 'Station is not blocked',
  NOT_CHARGING: 'Session is not currently charging',
  NOT_DRAFT: 'Only draft campaigns can be updated',
  NOT_IMPLEMENTED: 'Remote start on partner networks requires the OCPI Commands module',
  NOT_PENDING: 'Station is not pending approval',
  NOT_SUPPORTED: 'Not supported for OCPP 1.6',
  NOTIFICATION_EVENT_REQUIRED:
    'This notification is required for account access and cannot be turned off',
  OCPP_COMMAND_FAILED: 'OCPP command failed',
  OCPP_VERSION_MISMATCH: 'The command is for a different OCPP version than the station uses',
  OCTT_RUN_NOT_FOUND: 'Conformance run not found',
  OVERSUBSCRIPTION_EXCEEDED:
    'Total connected capacity (... kW) exceeds panel effective capacity (... kW)',
  PANEL_NOT_FOUND: 'Panel not found',
  PARTNER_NOT_CONNECTED: 'Partner must be connected to sync',
  PARTNER_NOT_FOUND: 'Partner not found',
  PASSWORD_REQUIRED: 'Password required when upgrading to SP1 or SP2',
  PAYMENT_CONFIG_NOT_FOUND: 'No payment config for this site',
  PAYMENT_FAILED: 'Payment failed',
  PAYMENT_METHOD_IN_USE: 'Payment method is in use by an active charging session',
  PAYMENT_METHOD_NOT_FOUND: 'Payment method not found',
  PAYMENT_METHOD_REQUIRED: 'Payment method required',
  PAYMENT_NOT_CONFIGURED: 'Payment not configured for this station',
  PAYMENT_NOT_FOUND: 'No payment record for this session',
  PAYMENT_OPERATION_PENDING:
    "The payment has an operation waiting for the provider's confirmation. Try again later.",
  PAYMENT_PREAUTH_FAILED: 'Payment authorization declined',
  PAYMENT_PROVIDER_CONNECTION_FAILED: 'Payment provider connection test failed',
  PAYMENT_PROVIDER_NOT_CONFIGURED: 'Payment provider is not configured',
  PAYMENT_PROVIDER_PERMISSION_MISSING:
    'The payment provider credential lacks a required permission',
  PAYMENT_PROVIDER_UPGRADE_PENDING:
    'A process older than v0.1.38 is still connected. Finish the upgrade, then select Adyen.',
  PAYMENT_RECORD_NOT_RECOVERABLE: 'Payment record is not in a recoverable state',
  PAYMENT_TOP_UP_FAILED: 'Payment top-up rejected',
  PAYMENT_WEBHOOK_EXISTS: 'An EVtivity webhook already exists for this provider',
  PAYOUT_ACCOUNT_EXISTS: 'The site already has a payout account',
  PAYOUT_ACCOUNT_NOT_READY: "The site's payout account cannot receive payments yet",
  PERMISSIONS_EXCEED_OWN: 'API key permissions must be a subset of your own permissions',
  PHONE_REGISTRATION_LIMITED:
    'Too many accounts were registered with this phone number. Try again later.',
  PKI_ROOT_REFRESH_FAILED: 'Root certificate refresh from the PKI provider failed',
  PNC_CONTRACT_NOT_FOUND: 'Plug & Charge contract not found',
  PNC_DISABLED: 'Plug & Charge is disabled',
  PORTAL_ALREADY_ACTIVE: 'Driver already has portal access',
  PORTAL_REGISTRATION_DISABLED:
    'Driver self-registration is disabled. Contact your operator to be invited.',
  PRE_AUTH_FAILED: 'Payment pre-authorization failed',
  PRICING_ASSIGNMENT_NOT_FOUND: 'No pricing group is assigned to this entity',
  PRICING_GROUP_NOT_FOUND: 'Pricing group not found',
  PRICING_GROUP_TARIFFS_IN_USE: 'Pricing group has tariffs referenced by charging sessions',
  PRICING_NOT_FOUND: 'No pricing found',
  PRIVATE_URL: 'Version URL must not point to a private or internal address',
  PROFILE_ID_ALLOC_FAILED: 'Could not allocate a free profileId',
  PROFILE_ID_IN_USE: 'profileId ... is already used by another template',
  PROVIDER_TEST_FAILED: 'Provider returned ...',
  PUSH_NOT_FOUND: 'Push not found',
  PUSH_REJECTED: 'Station rejected push: ...',
  RATE_LIMITED: 'Too many requests. Wait a moment and try again.',
  RECAPTCHA_FAILED: 'reCAPTCHA verification failed',
  RECAPTCHA_REQUIRED: 'reCAPTCHA token is required',
  RECAPTCHA_SECRET_REQUIRED: 'A reCAPTCHA secret key is required to enable reCAPTCHA',
  REFUND_EXCEEDS_REMAINING: 'Refund amount exceeds remaining ...',
  REFUND_TOP_UP_UNKNOWN:
    "This payment includes a top-up charge with no recorded payment id. Refund the top-up in the payment provider's dashboard.",
  REGION_NOT_FOUND: 'Region not found',
  REPORT_NOT_FOUND: 'Report not found',
  RESERVATION_BUFFER_ACTIVE:
    'This connector has an upcoming reservation and cannot start a new session',
  RESERVATION_CONFLICT: 'An active reservation already exists for this station',
  RESERVATION_CREATE_FAILED: 'Failed to create reservation',
  RESERVATION_DISABLED: 'Reservations are disabled (system-wide, site-level, or station-level)',
  RESERVATION_DURING_MAINTENANCE: 'Reservation falls within a scheduled maintenance window',
  RESERVATION_EXPIRES_TOO_SOON: 'Reservation must end at least 60 seconds in the future',
  RESERVATION_NOT_ACTIVE: 'Reservation is not active',
  RESERVATION_NOT_FOUND: 'Reservation not found',
  RESERVATION_REJECTED: 'Station rejected reservation: ...',
  RESERVATION_STARTS_IN_PAST: 'Reservation start time cannot be in the past',
  RESERVATION_TIMEOUT: 'Reservation command timed out',
  RESERVATION_TOO_LONG: 'Reservation cannot exceed ... hours',
  RESERVATION_WINDOW_TOO_SHORT: 'Reservation must end at least 60 seconds after it starts',
  RESET_NOT_REQUIRED: 'Password reset is not required',
  ROAMING_DISABLED: 'Roaming is disabled',
  ROLE_NOT_FOUND: 'Role does not exist',
  ROTATION_NOT_APPLICABLE: 'Credential rotation only applies to security profiles 1 and 2',
  RULE_NOT_FOUND: 'Rule not found',
  SCHEDULE_NOT_FOUND: 'Schedule not found',
  SCHEMA_NOT_FOUND: 'Schema not found',
  SECURITY_PROFILE_DOWNGRADE: 'A connected station cannot be moved to a lower security profile',
  SELF_EDIT_FORBIDDEN: 'Cannot edit your own role, status, or site access',
  SESSION_ALREADY_ACTIVE: 'You already have an active charging session',
  SESSION_CREATE_FAILED: 'Failed to create session',
  SESSION_NOT_FOUND: 'Session not found',
  SESSION_NOT_LINKED: 'Session not linked to this case',
  SESSION_REBILL_IN_PROGRESS: 'The session is being billed. Try again in a few minutes.',
  SESSION_REBILL_NOT_ELIGIBLE: 'This session cannot be billed',
  SESSION_REBILL_PAYMENT_PENDING:
    'The session has a payment the provider has not settled yet. Try again later.',
  SETTING_NOT_FOUND: 'Setting not found',
  SITE_HAS_STATIONS: 'Cannot delete site with stations. Remove or reassign stations first.',
  SITE_NOT_FOUND: 'Site not found',
  SITE_PAYMENT_CONFIG_IN_USE:
    "This site's payment configuration has payments and cannot be deleted. Disable it instead.",
  SMS_NOT_CONFIGURED: 'SMS provider not configured',
  SMS_SEND_FAILED: 'Failed to send SMS',
  SSO_DISABLED: 'SSO is not configured',
  START_REJECTED: 'Station rejected start request: ...',
  STATION_ALREADY_AVAILABLE: 'Station already has an available connector',
  STATION_ALREADY_IN_FLEET: 'Station is already in this fleet',
  STATION_ID_EXISTS: 'A station with this ID already exists',
  STATION_NOT_FOUND: 'Station not found',
  STATION_OFFLINE: 'Station is offline',
  STATION_REJECTED: 'Station rejected start: ...',
  STATION_SECURITY_CHANGE_REJECTED:
    'The station did not accept the security change; its current settings are unchanged',
  STATION_TIMEOUT: 'Station did not respond',
  STATION_TLS_URL_NOT_CONFIGURED:
    'The public TLS address for stations (OCPP_STATION_TLS_URL) is not configured',
  STATION_UNAVAILABLE: 'Station is unavailable',
  STATION_WATCH_NOT_FOUND: 'Watch not found',
  STATUS_CHECK_REJECTED: 'Station rejected the status check',
  STATUS_CHECK_TIMEOUT: 'Status check timed out. Replug the connector and try again.',
  STORAGE_CONNECTION_FAILED: 'Storage connection test failed',
  STORAGE_NOT_CONFIGURED: 'Attachment storage not configured',
  SUPPORT_AI_NOT_CONFIGURED: 'Support AI is not configured',
  SUPPORT_CASE_NOT_FOUND: 'Support case not found',
  SUPPORT_DISABLED: 'Support is disabled',
  TARIFF_IN_USE: 'Tariff is referenced by charging sessions and cannot be deleted',
  TARIFF_NOT_FOUND: 'Tariff not found',
  TARIFF_OVERLAP: 'Tariff overlaps with an existing tariff',
  TEMPLATE_NOT_FOUND: 'Template not found',
  TOKEN_DUPLICATE: 'Token already registered',
  TOKEN_IN_USE: 'Token is currently in use by an active charging session',
  TOKEN_NOT_FOUND: 'Token not found',
  TOO_MANY_WATCHES: 'You are watching too many stations',
  TOTP_NOT_CONFIGURED: 'TOTP not set up',
  TRANSACTION_NOT_FOUND: 'Transaction not found',
  UNAUTHORIZED: 'Unauthorized',
  UNKNOWN_ACTION: 'Unknown OCPP action',
  USER_NOT_FOUND: 'User not found',
  VALIDATION_ERROR: 'Validation error',
  VEHICLE_NOT_FOUND: 'Vehicle not found',
  VENDOR_NOT_FOUND: 'Vendor not found',
  VERIFICATION_RESEND_LIMITED: 'Too many verification emails. Wait before you request another one.',
  WEAK_PASSWORD: 'Password does not meet complexity requirements',
  WEBHOOK_NOT_CONFIGURED: 'Webhook not configured',
  WEBHOOK_SIGNATURE_INVALID: 'Invalid signature',
  WEBHOOK_SIGNATURE_MISSING: 'Missing webhook signature or credentials',
};
