// Copyright (c) 2024-2026 EVtivity. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1

// Static test material for the certificate signing tests: an EC P-256 CSR
// (C=US, O=OCTT, OU=OCTT, CN=OCTT-CS) and the certificate a test SubCA issued
// for it, valid until 2046. The SubCA key is not kept.

export const OCTT_CSR =
  '-----BEGIN CERTIFICATE REQUEST-----\nMIH4MIGfAgEAMD0xCzAJBgNVBAYTAlVTMQ0wCwYDVQQKDARPQ1RUMQ0wCwYDVQQL\nDARPQ1RUMRAwDgYDVQQDDAdPQ1RULUNTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD\nQgAEH7Uu7XxpOh33Y97SrY6xw5PfpdBL00he6ZN0aXm3ESWdIi9iThE+9bHghGmi\nlH4fqb1dMuID+e7dDLPy3+fCdaAAMAoGCCqGSM49BAMCA0gAMEUCIQCcFxBzTVC0\nvEbkj8/ByBSfuv5NVw7UvjlJOcfOiL2C3wIgK/ciZCYwnddQafaT+51liF1wTGlK\nGupeO9kuAwRAcvM=\n-----END CERTIFICATE REQUEST-----';

/** Leaf certificate followed by the issuing SubCA, as CertificateSigned carries it. */
export const OCTT_SIGNED_CERTIFICATE_CHAIN =
  '-----BEGIN CERTIFICATE-----\nMIIBbjCCARQCFFjNfcgOuFXgvHnqoK18HFCt+e7bMAoGCCqGSM49BAMCMDYxCzAJ\nBgNVBAYTAlVTMQ0wCwYDVQQKDARPQ1RUMRgwFgYDVQQDDA9PQ1RUIFRlc3QgU3Vi\nQ0EwHhcNMjYxMDAxMDQyMDA5WhcNNDYwOTI2MDQyMDA5WjA9MQswCQYDVQQGEwJV\nUzENMAsGA1UECgwET0NUVDENMAsGA1UECwwET0NUVDEQMA4GA1UEAwwHT0NUVC1D\nUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABB+1Lu18aTod92Pe0q2OscOT36XQ\nS9NIXumTdGl5txElnSIvYk4RPvWx4IRpopR+H6m9XTLiA/nu3Qyz8t/nwnUwCgYI\nKoZIzj0EAwIDSAAwRQIhANi0NVihd3ooWGTXIw9sv7qCC19ZoqQOw9fLDbJ8pFyc\nAiAk5rLYcQmoP0jTpyi1L2ljOaRm3fZywBhGJAFI7qFLbg==\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIBwDCCAWegAwIBAgIUZECvpIEtJpg5M81GyF1tIhfEW0wwCgYIKoZIzj0EAwIw\nNjELMAkGA1UEBhMCVVMxDTALBgNVBAoMBE9DVFQxGDAWBgNVBAMMD09DVFQgVGVz\ndCBTdWJDQTAeFw0yNjEwMDEwNDIwMDlaFw00NjA5MjYwNDIwMDlaMDYxCzAJBgNV\nBAYTAlVTMQ0wCwYDVQQKDARPQ1RUMRgwFgYDVQQDDA9PQ1RUIFRlc3QgU3ViQ0Ew\nWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT+qQsfHqmJiCAQJkymKj708QyTL0Rn\nP4b77NukVQE05xLIfskSpe2DLXc3lNd29/OKm4fFEDG46Iz4QDZA1JC6o1MwUTAd\nBgNVHQ4EFgQUdHkHYZNbQefOYBAsx1d/dEQsQKMwHwYDVR0jBBgwFoAUdHkHYZNb\nQefOYBAsx1d/dEQsQKMwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNHADBE\nAiBGD8rOkl+2S1veyMAx/QHmPXf9P81hVEgKUS8pXFkm2QIgBNCse6lUAVjkTD2Q\nd8v4ytiikkthrqvxTvMQxx90720=\n-----END CERTIFICATE-----';
